barterio/bartapp/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "bartapp"

urlpatterns = [
    path('', views.index, name="index"),
    path("register/", views.register, name="register"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('<int:pk>/<slug:category>/<slug:offer>/', views.offer_detail, name="offer_detail"),
    path('user_profile/<int:pk>/<slug:username>/', views.profile, name="profile"),
    path('user_profile/<int:pk>/<slug:username>/edit/', views.profile_edit, name="profile_edit"),
    path('title_search_results/', views.title_search, name="title_search_results"),
    path('category_search_results/<str:category>/', views.CategorySearchView.as_view(), name="category_search_results"),
    path('city_search_results/<str:city>/', views.CitySearchView.as_view(), name="city_search_results"),
    path('create_offer/', views.create_offer, name="create_offer"),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

barterio/bartapp/models.py
from django.db import models
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
import datetime
from django.core.validators import RegexValidator
from ckeditor.fields import RichTextField
from django.template.defaultfilters import slugify
from django.urls import reverse
from sorl.thumbnail import ImageField


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profile")
    date_of_birth = models.DateField()
    mobile = PhoneNumberField(unique=True)
    company_name = models.CharField(max_length=50, blank=True)
    company_description = RichTextField(blank=True)
    company_short_description = models.CharField(max_length=120, blank=True)
    company_account = models.CharField(max_length=26, blank=True)
    localisation = models.CharField(max_length = 50)
    transfer_data = RichTextField(blank=True)

    @property
    def is_adult(self):
        return datetime.date.today() - self.date_of_birth > datetime.timedelta(6567)
    
    def __str__(self):
        return f"This is {self.user.username}'s profile"
    
    def get_absolute_url(self):
        return reverse("bartapp:profile", args=[self.user.pk, self.user.username])


class Offer(models.Model):
    CATEGORIES_CHOICES = (
        ('art_spoz', 'Artykuły spożywcze'),
        ('edukacja', 'Edukacja'),
        ('ogrodnictwo', 'Ogrodnictwo'),
        ('zdrowie_uroda', "Zdrowie i uroda"),
        ('uslugi', 'Usługi'),
        ('prawo', "Prawo"),
        ('odziez_obuwie', "Odzież i Obuwie"),
        ('inne', "Inne")
    )

    STATUS_CHOICES = (
        ('draft', "Draft"),
        ('published', "Published")
    )

    TRANSFER_CHOICES = (
        ('gotowka', "Gotówka"),
        ('przelew', 'Przelew'),
        ('wymiana', 'Wymiana'),
        ('wymiana_gotowka', 'Wymiana + gotówka'),
        ('wymiana_przelew', 'Wymiana + przelew')
    )


    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="offers")
    title = models.CharField(max_length=50)
    slug=models.SlugField()
    date_published = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    category = models.CharField(max_length=20, choices=CATEGORIES_CHOICES)
    description = RichTextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    estimated_value = models.DecimalField(decimal_places=2, max_digits=10)
    transfer = models.CharField(max_length=20, choices=TRANSFER_CHOICES)
    localisation = models.CharField(max_length=50, default='')
    special = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        super(Offer, self).save(*args, **kwargs)
        self.slug = slugify(self.title)

    def get_absolute_url(self):
        return reverse("bartapp:offer_detail", args=[self.pk, self.category, self.slug])

    @property
    def has_max_photos(self):
        return self.images.count() >= 8

    class Meta:
        ordering = ('-date_published', )

class OfferImage(models.Model):
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, related_name="images")
    image = ImageField(upload_to="images/%Y/%m/%d", blank=True)

    def __str__(self):
        return self.offer.title

barterio/bartapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile, Offer, OfferImage

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email")

    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Nazwa użytkownika'
        self.fields['email'].label = 'Adres e-mail'
        self.fields['password'].label = 'Hasło'
        self.fields['password2'].label = 'Powtórz hasło'

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('date_of_birth', 'mobile', 'company_name', 'company_description', 'company_short_description', 'company_account', 'localisation', 'transfer_data')
    
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)
        self.fields['date_of_birth'].label = 'Data urodzenia'
        self.fields['mobile'].label = 'Telefon'
        self.fields['company_name'].label = 'Nazwa firmy (opcjonalnie)'
        self.fields['company_description'].label = 'Opis działalności (opcjonalnie)'
        self.fields['company_short_description'].label = 'Krótki opis działalności (będzie widoczny w każdym ogłoszeniu, opcjonalne)'
        self.fields['company_account'].label = 'Numer konta firmy (opcjonalnie)'
        self.fields['localisation'].label = 'Lokalizacja'
        self.fields['transfer_data'].label = 'Dane do przelewu (opcjonalnie)'


class OfferCreateForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ('title', 'category', 'description', 'estimated_value', 'transfer', 'localisation')
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)
        self.fields['title'].label = 'Tytuł'
        self.fields['category'].label = 'Kategoria'
        self.fields['description'].label = 'Opis'
        self.fields['estimated_value'].label = 'Szacowana wartość w PLN'
        self.fields['transfer'].label = 'Forma płatności'
        self.fields['localisation'].label = 'Lokalizacja'

class AddOfferImageForm(forms.Form):
    image = forms.ImageField(label='Obraz')

barterio/bartapp/views.py
from django.shortcuts import render
from django.views import generic
from .forms import RegisterForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from .models import Offer, OfferImage
from django.contrib.auth.decorators import login_required
from .forms import ProfileEditForm, OfferCreateForm, AddOfferImageForm
from django.http import HttpResponseForbidden, Http404, HttpResponseRedirect
from django.contrib import messages
from django.forms import modelformset_factory, formset_factory
from django.urls import reverse_lazy
from django.template.defaultfilters import slugify
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def index(request):
    special_offers = Offer.objects.filter(status="published", special=True)[:2]
    offers = Offer.objects.filter(status="published")
    return render(request, "bartapp/index.html", {'special_offers': special_offers, "offers": offers})
    

def offer_detail(request, pk, category, offer):
    offer = get_object_or_404(Offer, pk=pk, category=category, slug=offer)
    offer_images = offer.images.all()
    images = []
    for image in offer.images.all():
        try:
            images.append(image.image.url)
        except ValueError:
            continue

    return render(request, "bartapp/offer_detail.html", {"offer": offer, "images":images})

# 
# Creating a new user and adding him/her to a database
def register(request):
    if request.method == "POST":
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, "bartapp/register_done.html", {'new_user': new_user})

    else:
        user_form = RegisterForm()
    return render (request, "bartapp/register.html", {'user_form': user_form})


@login_required
def profile(request, pk, username):
    user = get_object_or_404(User, pk=pk, username=username)
    return render(request, "bartapp/profile.html", {'user': user})

@login_required
def profile_edit(request, pk, username):
    user = get_object_or_404(User, pk=pk, username=username)
    profile = user.profile
    form = ProfileEditForm(request.POST or None, instance=profile)
    if request.user.username != user.username:
        return HttpResponseForbidden
    if form.is_valid():
        messages.success(request, "Twój profil został zaktualizowany pomyślnie")
        form.save()
        
    return render(request, "bartapp/profile_edit.html", {'user': user, "form":form})

def title_search(request):
    if request.method == "GET":
        title=request.GET.get('title')
        offers = Offer.objects.filter(title__icontains=title, status="published") 
        return render(request, "bartapp/search_results_name.html", {"offers": offers})
    else:
        return Http404

class CategorySearchView(generic.ListView):
    model=Offer
    def get_queryset(self):
        return Offer.objects.filter(category=self.kwargs['category'], status="published") 
    context_object_name="offers"
    template_name="bartapp/search_results.html"
    paginate_by = 3

class CitySearchView(generic.ListView):
    model=Offer
    def get_queryset(self):
        return Offer.objects.filter(localisation=self.kwargs['city'], status="published") 
    context_object_name="offers"
    template_name="bartapp/search_results.html"
    paginate_by = 3

@login_required
def create_offer(request):
    # ImageFormset = modelformset_factory(OfferImage, form=AddOfferImageForm, extra=7)
    ImageFormset = formset_factory(AddOfferImageForm, extra=7)
    if request.method == "POST":
        offer_form = OfferCreateForm(request.POST)
        image_formset = ImageFormset(request.POST, request.FILES)
        if offer_form.is_valid() and image_formset.is_valid():
            new_offer = offer_form.save(commit=False)
            new_offer.author = request.user
            new_offer.status = "draft"
            new_offer.slug = slugify(new_offer.title)
            new_offer.save()
            for form in image_formset.cleaned_data:
                image = form.get('image')
                new_image = OfferImage(offer=new_offer, image=image)
                new_image.save()
            return HttpResponseRedirect('/')
            
    else:
        offer_form = OfferCreateForm()
        image_formset = formset_factory(AddOfferImageForm, extra=7)
        return render(request, "bartapp/create_offer.html", {'offer_form': offer_form, "image_formset": image_formset})

barterio/bartapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="pl">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Barterio App</title>
    <!-- Tags -->
    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'bartapp/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'bartapp/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'bartapp/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'bartapp/favicon/site.webmanifest' %}">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bartapp/styles/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bartapp/fontello/css/fontello.css' %}">

    <title>{% block title %}Strona glowna{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-brand">
        <a class="navbar-brand" href="{% url 'bartapp:index' %}"><img src="{% static 'bartapp/images/ebarterio-white.svg' %}"
                alt="Barterio logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav px-3">
                <form class="form-inline my-2 my-lg-0 order-lg-3 position-relative" method ="GET" action="{% url 'bartapp:title_search_results' %}">
                    <input name="title" class="form-control mr-sm-2 d-flex w-100" type="search" placeholder="Wyszukaj"
                        aria-label="Search">
                    <button class="btn btn-outline-success my-sm-0 position-absolute r-0 search-bttn" type="submit"><img
                            src="{% static 'bartapp/icons/search.svg' %}" alt="wyszukaj"></button>
                </form>
                <li class="nav-item dropdown d-flex align-items-center px-3 order-lg-1">
                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Wybierz kategorię
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'bartapp:category_search_results' category='art_spoz' %}">Art. spożywcze</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:category_search_results' category='odziez_obuwie' %}">Odzież i obuwie</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:category_search_results' category='zdrowie_uroda' %}">Zdrowie i uroda</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:category_search_results' category='ogrodnictwo' %}">Ogrodnictwo</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:category_search_results' category='edukacja' %}">Edukacja</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:category_search_results' category='uslugi' %}">Usługi</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:category_search_results' category='inne' %}">Inne</a>
                    </div>
                </li>
                <li class="nav-item dropdown order-lg-2">
                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="padding: 6px">
                        <span style="padding: 6px">Wybierz miasto</span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'bartapp:city_search_results' city='Warszawa' %}">Warszawa</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:city_search_results' city='Kraków' %}">Kraków</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:city_search_results' city='Wrocław' %}">Wrocław</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:city_search_results' city='Poznań' %}">Poznań</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:city_search_results' city='Katowice' %}">Katowice</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:city_search_results' city='Gdańsk' %}">Gdańsk</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:city_search_results' city='Łódź' %}">Łódź</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'bartapp:city_search_results' city='Szczecin' %}">Szczecin</a>
                        <div class="dropdown-divider"></div>
                        
                    </div>
                </li>
                <div class="dropdown-divider d-lg-none"></div>
                <li class="nav-item order-lg-4 d-flex justify-content-between align-items-center">
                    {% if request.user.is_authenticated %}
                    <a class="mx-lg-2 text-light text-decoration-none"
                        href="{{ request.user.profile.get_absolute_url }}">
                        <i style="font-size: 30px" class="icon-user"></i></a>
                    <a class="text-light text-decoration-none" style="padding: 0 0.5rem;" href="{% url 'bartapp:logout' %}">Wyloguj</a>
                    {% else %}
                    <a class="text-light text-decoration-none ml-lg-3" href="{% url 'bartapp:login' %}">Zaloguj</a>
                    {% endif %}
                    <!-- <a style="text-decoration: none; color: white;"
                        class="align-items-center order-lg-4 mr-2 ml-4 d-none d-lg-flex" href="/login">
                        <i style="color: color; font-size: 30px" class="icon-user"></i>
                    </a> -->
                </li>
            </ul>
        </div>
    </nav>
    <section>{% block content %}{% endblock %}</section>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>