barterio/bartapp/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "bartapp"

urlpatterns = [
    path('', views.index, name="index"),
    path("register/", views.register, name="register"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('<int:pk>/<slug:category>/<slug:offer>/', views.offer_detail, name="offer_detail"),
    path('user_profile/<int:pk>/<slug:username>/', views.profile, name="profile"),
    path('user_profile/<int:pk>/<slug:username>/edit/', views.profile_edit, name="profile_edit"),
    path('title_search_results/', views.title_search, name="title_search_results"),
    path('category_search_results/<str:category>/', views.CategorySearchView.as_view(), name="category_search_results"),
    path('city_search_results/<str:city>/', views.CitySearchView.as_view(), name="city_search_results"),
    path('create_offer/', views.create_offer, name="create_offer"),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

barterio/bartapp/models.py
from django.db import models
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
import datetime
from django.core.validators import RegexValidator
from ckeditor.fields import RichTextField
from django.template.defaultfilters import slugify
from django.urls import reverse
from sorl.thumbnail import ImageField


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profile")
    date_of_birth = models.DateField()
    mobile = PhoneNumberField(unique=True)
    company_name = models.CharField(max_length=50, blank=True)
    company_description = RichTextField(blank=True)
    company_short_description = models.CharField(max_length=120, blank=True)
    company_account = models.CharField(max_length=26, blank=True)
    localisation = models.CharField(max_length = 50)
    transfer_data = RichTextField(blank=True)

    @property
    def is_adult(self):
        return datetime.date.today() - self.date_of_birth > datetime.timedelta(6567)
    
    def __str__(self):
        return f"This is {self.user.username}'s profile"
    
    def get_absolute_url(self):
        return reverse("bartapp:profile", args=[self.user.pk, self.user.username])


class Offer(models.Model):
    CATEGORIES_CHOICES = (
        ('art_spoz', 'Artykuły spożywcze'),
        ('edukacja', 'Edukacja'),
        ('ogrodnictwo', 'Ogrodnictwo'),
        ('zdrowie_uroda', "Zdrowie i uroda"),
        ('uslugi', 'Usługi'),
        ('prawo', "Prawo"),
        ('odziez_obuwie', "Odzież i Obuwie"),
        ('inne', "Inne")
    )

    STATUS_CHOICES = (
        ('draft', "Draft"),
        ('published', "Published")
    )

    TRANSFER_CHOICES = (
        ('gotowka', "Gotówka"),
        ('przelew', 'Przelew'),
        ('wymiana', 'Wymiana'),
        ('wymiana_gotowka', 'Wymiana + gotówka'),
        ('wymiana_przelew', 'Wymiana + przelew')
    )


    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="offers")
    title = models.CharField(max_length=50)
    slug=models.SlugField()
    date_published = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    category = models.CharField(max_length=20, choices=CATEGORIES_CHOICES)
    description = RichTextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    estimated_value = models.DecimalField(decimal_places=2, max_digits=10)
    transfer = models.CharField(max_length=20, choices=TRANSFER_CHOICES)
    localisation = models.CharField(max_length=50, default='')
    special = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        super(Offer, self).save(*args, **kwargs)
        self.slug = slugify(self.title)

    def get_absolute_url(self):
        return reverse("bartapp:offer_detail", args=[self.pk, self.category, self.slug])

    @property
    def has_max_photos(self):
        return self.images.count() >= 8

    class Meta:
        ordering = ('-date_published', )

class OfferImage(models.Model):
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, related_name="images")
    image = ImageField(upload_to="images/%Y/%m/%d", blank=True)

    def __str__(self):
        return self.offer.title

barterio/bartapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile, Offer, OfferImage

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email")

    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Nazwa użytkownika'
        self.fields['email'].label = 'Adres e-mail'
        self.fields['password'].label = 'Hasło'
        self.fields['password2'].label = 'Powtórz hasło'

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('date_of_birth', 'mobile', 'company_name', 'company_description', 'company_short_description', 'company_account', 'localisation', 'transfer_data')
    
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)
        self.fields['date_of_birth'].label = 'Data urodzenia'
        self.fields['mobile'].label = 'Telefon'
        self.fields['company_name'].label = 'Nazwa firmy (opcjonalnie)'
        self.fields['company_description'].label = 'Opis działalności (opcjonalnie)'
        self.fields['company_short_description'].label = 'Krótki opis działalności (będzie widoczny w każdym ogłoszeniu, opcjonalne)'
        self.fields['company_account'].label = 'Numer konta firmy (opcjonalnie)'
        self.fields['localisation'].label = 'Lokalizacja'
        self.fields['transfer_data'].label = 'Dane do przelewu (opcjonalnie)'


class OfferCreateForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ('title', 'category', 'description', 'estimated_value', 'transfer', 'localisation')
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)
        self.fields['title'].label = 'Tytuł'
        self.fields['category'].label = 'Kategoria'
        self.fields['description'].label = 'Opis'
        self.fields['estimated_value'].label = 'Szacowana wartość w PLN'
        self.fields['transfer'].label = 'Forma płatności'
        self.fields['localisation'].label = 'Lokalizacja'

class AddOfferImageForm(forms.Form):
    image = forms.ImageField(label='Obraz')

barterio/bartapp/views.py
from django.shortcuts import render
from django.views import generic
from .forms import RegisterForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from .models import Offer, OfferImage
from django.contrib.auth.decorators import login_required
from .forms import ProfileEditForm, OfferCreateForm, AddOfferImageForm
from django.http import HttpResponseForbidden, Http404, HttpResponseRedirect
from django.contrib import messages
from django.forms import modelformset_factory, formset_factory
from django.urls import reverse_lazy
from django.template.defaultfilters import slugify
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def index(request):
    special_offers = Offer.objects.filter(status="published", special=True)[:2]
    offers = Offer.objects.filter(status="published")
    return render(request, "bartapp/index.html", {'special_offers': special_offers, "offers": offers})
    

def offer_detail(request, pk, category, offer):
    offer = get_object_or_404(Offer, pk=pk, category=category, slug=offer)
    offer_images = offer.images.all()
    images = []
    for image in offer.images.all():
        try:
            images.append(image.image.url)
        except ValueError:
            continue

    return render(request, "bartapp/offer_detail.html", {"offer": offer, "images":images})

# 
# Creating a new user and adding him/her to a database
def register(request):
    if request.method == "POST":
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, "bartapp/register_done.html", {'new_user': new_user})

    else:
        user_form = RegisterForm()
    return render (request, "bartapp/register.html", {'user_form': user_form})


@login_required
def profile(request, pk, username):
    user = get_object_or_404(User, pk=pk, username=username)
    return render(request, "bartapp/profile.html", {'user': user})

@login_required
def profile_edit(request, pk, username):
    user = get_object_or_404(User, pk=pk, username=username)
    profile = user.profile
    form = ProfileEditForm(request.POST or None, instance=profile)
    if request.user.username != user.username:
        return HttpResponseForbidden
    if form.is_valid():
        messages.success(request, "Twój profil został zaktualizowany pomyślnie")
        form.save()
        
    return render(request, "bartapp/profile_edit.html", {'user': user, "form":form})

def title_search(request):
    if request.method == "GET":
        title=request.GET.get('title')
        offers = Offer.objects.filter(title__icontains=title, status="published") 
        return render(request, "bartapp/search_results_name.html", {"offers": offers})
    else:
        return Http404

class CategorySearchView(generic.ListView):
    model=Offer
    def get_queryset(self):
        return Offer.objects.filter(category=self.kwargs['category'], status="published") 
    context_object_name="offers"
    template_name="bartapp/search_results.html"
    paginate_by = 3

class CitySearchView(generic.ListView):
    model=Offer
    def get_queryset(self):
        return Offer.objects.filter(localisation=self.kwargs['city'], status="published") 
    context_object_name="offers"
    template_name="bartapp/search_results.html"
    paginate_by = 3

@login_required
def create_offer(request):
    # ImageFormset = modelformset_factory(OfferImage, form=AddOfferImageForm, extra=7)
    ImageFormset = formset_factory(AddOfferImageForm, extra=7)
    if request.method == "POST":
        offer_form = OfferCreateForm(request.POST)
        image_formset = ImageFormset(request.POST, request.FILES)
        if offer_form.is_valid() and image_formset.is_valid():
            new_offer = offer_form.save(commit=False)
            new_offer.author = request.user
            new_offer.status = "draft"
            new_offer.slug = slugify(new_offer.title)
            new_offer.save()
            for form in image_formset.cleaned_data:
                image = form.get('image')
                new_image = OfferImage(offer=new_offer, image=image)
                new_image.save()
            return HttpResponseRedirect('/')
            
    else:
        offer_form = OfferCreateForm()
        image_formset = formset_factory(AddOfferImageForm, extra=7)
        return render(request, "bartapp/create_offer.html", {'offer_form': offer_form, "image_formset": image_formset})

barterio/bartapp/templates/bartapp/create_offer.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div style="text-align: center; padding: 30px;">
    <form action='.' method="POST" enctype='multipart/form-data' >
        {% csrf_token %}
        {{ offer_form.media }}
        {{ offer_form|crispy }}

        {{ image_formset.management_form }}
        {{ image_formset|crispy }}
        <!-- {% for form in image_formset %}
            {{ form|crispy }}
        {% endfor %} -->
        <input type="submit" name="submit" value="Add"/>      
    </form>
</div>
{% endblock %}

barterio/bartapp/templates/bartapp/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
    <div style="width: 300px; padding: 20px; text-align: center; margin: 0 auto;">
        <button style="width: 50px; height: 50px;  border-radius: 50%; background-color: #2EB67B; margin: 0 auto; color: white; font-weight: bold; font-size: 20px">+</button><span style="margin-left: 10px;"><a style="text-decoration: none; font-weight: bold;" href="{% url 'bartapp:create_offer' %}">DODAJ OFERTĘ</a></span>
    </div>
{% else %}
{% endif %}
<div class="hero container">
    <div class="row">
        <div class="col">
            <h1 class="my-4 my-md-5 text-center">
                Sprzedawaj<br>
                Wymieniaj<br>
                Zarabiaj
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="text-center">
                <img src="{% static 'bartapp/images/hero.svg' %}" alt="sprzedawaj online">
            </div>
        </div>
    </div>
    <div class="row justify-content-center mb-4 mb-md-5">
        <div class="col col-md-8 text-center">
            {% if request.user.is_authenticated %}
            <h5 class="my-4">Możesz już zacząć przeszukiwać oferty i wystawiać własne :)</h5>
            {% else %}
            <h5 class="my-4">
                Dołącz do ogólnopolskiej platfromy wymiany towarów i&nbsp;usług
            </h5>
            {% endif %}
            {% if user.is_authenticated %}
          
            {% else %}
            <a class="btn btn-lg text-light text-decoration-none text-light"
                href="{% url 'bartapp:register' %}">Zarejestruj się</a>
            <p class="mt-4 mb-0 text-muted">Masz już konto?</p>
            <a class="btn btn-link" href="{% url 'bartapp:login' %}">Zaloguj</a>
            {% endif %}
        </div>
    </div>
</div>

<div class="container my-4 my-md-5">
    <div class="grid-wrapper">

        {% for offer in offers %}
        
        <div class="grid-item">
            <div class="card ">
                <a href="{{ offer.get_absolute_url }}">
                <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active" data-interval="8000">
                            <div class="d-block w-100 bg-img"
                                style="background-image: url({{ offer.images.first.image.url }});">
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                </a>
                <div class="card-body pb-0">
                    <h5><strong>{{ offer.title }}</strong></h5>
                    <small class="text-muted">Opublikowano: {{ offer.date_published|timesince }}</small>
                </div>
                <div class="card-body py-2 pt-0">
                    <small class="card-text py-1 px-2 text-light rounded bg-primary">{{ offer.category }}</small>
                    <small class="card-text py-1 px-2 text-light rounded bg-brand">{{ offer.transfer }}</small></div>
                <div class="dropdown-divider"></div>
                <div class="card-body pt-2">
                    <p class="card-text" style="text-align: center;">Autor: <b>{{ offer.author.username }}</b></p>
                </div>
                <div class="card-header d-flex justify-content-between" style="border-bottom: none;">
                    <p class="mb-0">Szacowana wartość:</p>
                    <h5 class="card-title text-right mb-0"> {{ offer.estimated_value }}</h5>
                </div>
            </div>
        </div>
        
        {% endfor %}
    </div>
{% endblock %}

barterio/bartapp/templates/bartapp/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
 Logowanie
{% endblock title %}

{% block content %}
<h1> Logowanie </h1>
<p style="text-align: center"> Wypełnij poniższy formualarz </h1>
<form action="." method="post" >
    {{ form|crispy }}
    {% csrf_token %}
    <p><input type="submit" value="Zaloguj"></p>
</form>
{% endblock content %}

barterio/bartapp/templates/bartapp/offer_detail.html
{% extends 'base.html' %}
{% load static %}
​
{% block content %}
<div class="container my-4 my-md-5">
    <div class="grid-wrapper" style="text-align: center; grid-template-columns: repeat(auto-fill, minmax(auto, 1200px));">
        <div class="grid-item">
            <div class="card">
                <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active" data-interval="8000">
                            <div class="d-block bg-img"
                                style="background-image: url({{ images.0 }});">
                            </div>
                        </div>
                        {% for image in images %}
                       
                                {% if forloop.counter > 1 %}
                                <div class="carousel-item" data-interval="8000">
                                    <div class="d-block bg-img" style="background-image: url({{ image }});">
                                    </div>
                                </div>
                                {% endif %}
                         
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <div class="card-body pb-0">
                    <h5><strong>{{ offer.title }}</strong></h5>
                    <small class="text-muted">Opublikowano: {{ offer.date_published|timesince }}</small>
                </div>
                <div class="card-body py-2 pt-0">
                    <small class="card-text py-1 px-2 text-light rounded bg-primary">{{ offer.get_category_display }}</small>
                    <small class="card-text py-1 px-2 text-light rounded bg-brand">{{ offer.get_transfer_display }}</small></div>
                <div class="dropdown-divider"></div>
                <div class="card-body pt-2">
                    <p class="card-text">Autor: <b><a style="text-decoration: none; color: black;" href="{{ offer.author.profile.get_absolute_url}}">{{ offer.author.username }}</a></b>
                    {% if request.user.is_authenticated %}
                    <br />
                    Telefon: {{ offer.author.profile.mobile.national_number }}
                    {% endif %}
                    </p>
                </div>
                <div class="dropdown-divider"></div>
                <div class="card-body pt-2">
                    <p class="card-text">
                        <h2> OPIS </h2>
                        {{ offer.description|safe }}
                    </p>
                </div>
                <div class="card-header d-flex justify-content-between" style="border-bottom: none;">
                    <p class="mb-0">Szacowana wartość:</p>
                    <h5 class="card-title text-right mb-0"> {{ offer.estimated_value }} zł</h5>
                </div>
            </div>
        </div>
        
    </div>
</div>
{% endblock %}

barterio/bartapp/templates/bartapp/profile.html
{% extends 'base.html' %}

{% block content %}
<div style="width: 700px; padding: 15px; margin: 0 auto; text-align: center;">
    <h1 style="display: inline-block">Profil użytkownika {{ user.username }}</h1> 
    
    {% if request.user.username == user.username %}
    <span><a href="{% url 'bartapp:profile_edit' pk=user.pk username=user.username %}">Edytuj</a></span>
    {% endif %}

    <h2 style="text-align: center; padding: 20px 0">OPIS DZIAŁALNOŚCI</h2>
    <p>{{ user.profile.company_description|safe }}</p>

    <h2 style="text-align: center; padding: 20px 0">DANE DO PRZELEWU</h2>
    <p>{{ user.profile.transfer_data|safe }}</p>

    <h2 style="text-align: center; padding: 20px 0">OFERTY</h2>

    {% for offer in user.offers.all %}
        <a href="{{ offer.get_absolute_url }}"><h5 style="text-align: center; color: black">{{ offer.title }}</h5></a>
    {% endfor %}
{% endblock %}
</div>

barterio/bartapp/templates/bartapp/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    <p>Możesz powrócić do swojego <a href="{{ request.user.profile.get_absolute_url }}">profilu.</a></p>
</ul>
{% endif %}




    <form action="." method="post" style="text-align: center; margin-top: 20px;">
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <input type="submit" value="Aktualizuj profil" style="margin-left: auto; margin-right: auto;">
    
    </form>
{% endblock %}

barterio/bartapp/templates/bartapp/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
    <style>
        #hint_id_username {
            display: none;
        }

        .help-block {
            display: none;
        }
    </style>
{% endblock %}
{% block title %}Utwórz konto{% endblock title %}

{% block content %}

<div class="container my-4"
style="text-align: center;">
    <div class="row">
        <h4 class="col col-md-10 my-4 px-0" style="text-align: center; margin: 0 auto; font-weight: bold;">Wypełnij poniższy formularz, aby się zarejestrować </h4>
        <div class="col col-md-8 col-lg-6 mx-auto">
            
            <form action='.' method="post">
                {{ user_form|crispy }}
                {% csrf_token %}
                <input class="btn btn-primary my-4" type="submit" value="Utwórz konto">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

barterio/bartapp/templates/bartapp/register_done.html
{% extends 'base.html' %}

{% block title %}
Witaj
{% endblock title %}

{% block content %}
    <h1> Witaj {{ user.first_name }} 
    <p>Twoje konto zostało utworzone. Możesz się już <a href="{% url 'bartapp:login' %}"> zalogować </a> </p>
{% endblock content %}

barterio/bartapp/templates/bartapp/search_results.html
{% extends 'base.html' %}

{% block head %}
<style>
    .article:hover {background-color: rgb(197, 195, 195);}
.article:hover h2 {color: green; text-decoration: underline;}
</style>
{% endblock %}
{% block content %}

<!-- <div class="wrapper" style="width: 600px; padding: 20px; margin: 0 auto"></div> -->
        <!-- {% for offer in offers %}
            <div class="blog_post" >
                <img style="height: 100%; width: 100px; margin-top: 10px;" src="{{ offer.images.first.image.url }}" />
                <a style="text-decoration: none; color: black" href="{{ offer.get_absolute_url }}"><h5 style="display: inline-block; padding:0; margin:0">{{ offer.title }}</h5></a>
                <i style="font-size: 10px;">Opublikowane przez</i> <b style="font-size: 10px;">{{ offer.author.username }}</b> <i style="font-size: 10px;">on {{ offer.date_published }}</i>
                <hr>
                <p>{{ offer.description|safe|truncatechars:40 }}</p>
            </div>
        {% endfor %} -->
        <div id="last_20_on_the_left" 
        style="width: 750px;
        background-color: white;
        /* float: left; */
        margin: 0 auto;
        padding: 30px 0px;">
                {% for offer in offers %}
                <a href="{{ offer.get_absolute_url }}">
                    <article class="article" style="color: black;
                    font-size: 0.85em;
                    text-align: justify;
                    line-height: 1.5em;">    
                        <div class="post_image" style="float: left;"><img style="width: 200px;
                        height: 125px;" src="{{ offer.images.first.image.url }}"></div>
                        <div class="post_data" style=" float: left;
                        padding: 5px;
                        width: 500px;
                        word-wrap: break-word;
                        text-align: left;">
                            <div class="post_header">
                                <h2>{{ offer.title|title|truncatechars:30 }}</h2>
                                <i style="font-size: 0.9em;
                                font-weight: lighter;">{{ offer.date_published|timesince }} by {{ offer.author.username }}</i>
                            </div>
                            <div class="post_text" style="width: 500px;
                            height: 55px;
                            font-weight: lighter;
                            text-align: left;
                            word-wrap: break-word;
                            height: 75px;">
                                <p class="post_description_normal">{{ offer.description|safe|truncatechars:40 }}</p>
                                <!-- <p class="post_description_sm">{{ post.description|truncatechars:30 }}</p> -->
                            </div>
                        </div>
                        <div style="clear: both"></div>
                        
                    </article>
                </a>

                
                {% endfor %}
                
                <div style="text-align: center">
                    <span>
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; pierwsza</a>
                            <a href="?page={{ page_obj.previous_page_number }}">poprzednia</a>
                        {% endif %}
        
                        <span>{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
        
                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">następna</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">ostatnia &raquo;</a>
                        {% endif %}
                    </span>
                </div>
 
    </div>


{% endblock %}

barterio/bartapp/templates/bartapp/search_results_name.html
{% extends 'base.html' %}

{% block head %}
<style>
    .article:hover {background-color: rgb(197, 195, 195);}
.article:hover h2 {color: green; text-decoration: underline;}
</style>
{% endblock %}

{% block content %}
<div id="last_20_on_the_left" 
style="width: 750px;
background-color: white;
/* float: left; */
margin: 0 auto;
padding: 30px 0;">
        {% for offer in offers %}
        <a href="{{ offer.get_absolute_url }}">
            <article class="article" style="color: black;
            font-size: 0.85em;
            text-align: justify;
            line-height: 1.5em;">    
                <div class="post_image" style="float: left;"><img style="width: 200px;
                height: 125px;" src="{{ offer.images.first.image.url }}"></div>
                <div class="post_data" style=" float: left;
                padding: 5px;
                width: 500px;
                word-wrap: break-word;
                text-align: left;">
                    <div class="post_header">
                        <h2>{{ offer.title|title|truncatechars:30 }}</h2>
                        <i style="font-size: 0.9em;
                        font-weight: lighter;">{{ offer.date_published|timesince }} by {{ offer.author.username }}</i>
                    </div>
                    <div class="post_text" style="width: 500px;
                    height: 55px;
                    font-weight: lighter;
                    text-align: left;
                    word-wrap: break-word;
                    height: 75px;">
                        <p class="post_description_normal">{{ offer.description|safe|truncatechars:40 }}</p>
                        <!-- <p class="post_description_sm">{{ post.description|truncatechars:30 }}</p> -->
                    </div>
                </div>
                <div style="clear: both"></div>
                
            </article>
        </a>
        {% endfor %}

</div>

{% endblock %}